# Generated by Django 5.0.1 on 2024-04-22 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0003_alter_book_is_bestselling'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='is_bestselling',
            new_name='is_bestseller',
        ),
    ]
